### PR TITLE
[S03-smart-contracts/M2-intro-to-truffle/L2-intro-tutorial/] Fixes missing link #201

### PR DESCRIPTION
**Pull request by parseb**
added link. 
"more details on migrations can be found in Truffle’s documentation"
https://www.trufflesuite.com/docs/truffle/getting-started/running-migrations

### CODE REVIEW

**Comment by parseb** [comment]
@cooganb Can you give me a hint as to what I am doing wrong here. I do not want to merge all commits and change 19 files.

**Comment by cooganb** [comment]
@parseb oh my! Yes, I'm about to go to bed but will check in the morning! This is an impressive problem!

**Comment by parseb** [comment]
**staging** branch is - is 4 commits ahead, 42 commits **behind main.** 

My branch is from main, so it would add to staging the changes that are already in main. 
That's the only explanation I can come up with. Don't know how to avoid it.

**Comment by ConsenSys-Academy** [comment]
@parseb Would you mind resubmitting this with just your change? So start totally fresh, there's just been too many commits in the meanwhile!

**Pull request closed without merging**
