### PR TITLE
Converting remaining .html files into .md #108

### PR DESCRIPTION
**Pull request by CodeFrite**
Hello,

Please find in this pull request the converted .md files.

I have done it with a short python script in which I used the suggested Markdown library (thank you for the advice) and a regex expression ("[^!]\[.*?\]\(.*?\)") in order to locate the links (not the images which begin with !) and appending the {target=_blank}

Please note that since the files have been renamed, we cannot check the changes with a simple diff. If needed I can rerun the script and can create a new pull request without the renaming.

I have checked a few files and they seem ok. I suppose that the links not opening in a new window on GitHub is normal and will only work on Consensys website.

Thank you!

Hadi

### CODE REVIEW

**Comment by ConsenSys-Academy** [comment]
@CodeFrite Thank you so much for this, Hadi, this is really huge and thank you for taking the time to get a good script together!

A few points:
• As mentioned in the issue, I'd feel more comfortable starting off with just four or five files changed, not all at once. That way, if there is an unseen error, we don't break the whole course

If it's not too much trouble, would you mind just doing four or five files at first?

**Comment by CodeFrite** [comment]
Hello,

It is a real pleasure to (try to) contribute.

I thought it would be easier to just create a new PR instead of reverting 164 changes out of 174 changes. You can find it here:

https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/pull/131

. : Best Regards : .

Hadi

**Comment by CodeFrite** [comment]
If it can help anyone, please find below the python script (I wrote it just to get the work done so it is probably not quite efficient). 

If https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/pull/131 is ok, do not hesitate to ask me to create a pull request for the remaining items. I will be glad to help.

**Comment by CodeFrite** [comment]
```
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 19 22:32:42 2021

@author: Hadi
"""
import re
from markdownify import markdownify as md

# Paths to the files to convert
files_path=[
    "./docs/S01-fundamentals/M0-intro/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L1-pub-key-crypto/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L2-pub-key-crypto-additional/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L3-hashing/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L4-hashing-additional/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L8-crypto-wars-history/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L6-digital-sig-additional/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L8a-crypto-wars-video/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L5-digital-sig/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L7a-eth-101/index.html",
    "./docs/S01-fundamentals/M1-cryptography/L7-crypto-fundamentals-playground/index.html",
    "./docs/S01-fundamentals/M2-consensus/L9-blockchain-fork/index.html",
    "./docs/S01-fundamentals/M2-consensus/L2-consensus-additional/index.html",
    "./docs/S01-fundamentals/M2-consensus/L11-consensus-conclusion/index.html",
    "./docs/S01-fundamentals/M2-consensus/L1-consensus-intro/index.html",
    "./docs/S01-fundamentals/M2-consensus/L8-pow-in-ethereum/index.html",
    "./docs/S01-fundamentals/M2-consensus/L5-trustless-consensus/index.html",
    "./docs/S01-fundamentals/M2-consensus/L10-alt-consensus/index.html",
    "./docs/S01-fundamentals/M2-consensus/L6-what-is-a-block/index.html",
    "./docs/S01-fundamentals/M2-consensus/L3-raft/index.html",
    "./docs/S01-fundamentals/M2-consensus/L7-chain-of-blocks/index.html",
    "./docs/S01-fundamentals/M2-consensus/L4-nodes-and-networks/index.html",
    "./docs/S01-fundamentals/M3-ag-blockchain/L1-mental-model/index.html",
    "./docs/S01-fundamentals/M3-ag-blockchain/L4-when-to-use/index.html",
    "./docs/S01-fundamentals/M3-ag-blockchain/L2-configurations/index.html",
    "./docs/S01-fundamentals/M3-ag-blockchain/L3-public-private-networks/index.html",
    "./docs/S01-fundamentals/M4-bitcoin/L1-history-and-development/index.html",
    "./docs/S01-fundamentals/M5-wallets/L1-what-is-a-wallet/index.html",
    "./docs/S01-fundamentals/M5-wallets/L2-intro-to-mm/index.html",
    "./docs/S01-fundamentals/M5-wallets/L4-secure-extensible-javascript/index.html",
    "./docs/S01-fundamentals/M5-wallets/L5-mm-workshop/index.html",
    "./docs/S01-fundamentals/M5-wallets/L3-mm-lavamoat/index.html",
    "./docs/S01-fundamentals/M5-wallets/L3-security-considerations/index.html",
    "./docs/S02-ethereum/M1-background/index.html",
    "./docs/S02-ethereum/M2-accounts/L3-nodes/index.html",
    "./docs/S02-ethereum/M2-accounts/L2-generating-accounts/index.html",
    "./docs/S02-ethereum/M2-accounts/L1-accounts/index.html",
    "./docs/S02-ethereum/M3-state/L3-eth-structure/index.html",
    "./docs/S02-ethereum/M3-state/L2-gas-and-fees/index.html",
    "./docs/S02-ethereum/M3-state/L8-networks/index.html",
    "./docs/S02-ethereum/M3-state/L6-playing-with-merkle-trees/index.html",
    "./docs/S02-ethereum/M3-state/L4-txn-tutorial/index.html",
    "./docs/S02-ethereum/M3-state/L7-1559/index.html",
    "./docs/S02-ethereum/M3-state/L1-txns/index.html",
    "./docs/S02-ethereum/M3-state/L5-merkle-trees/index.html",
    "./docs/S03-smart-contracts/M1-mental-model/L1-mental-model-sc/index.html",
    "./docs/S03-smart-contracts/M2-intro-to-truffle/L2-intro-tutorial/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L4-storage-and-memory/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L6-abi/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L1-background-context/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L3-functions/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L8-factory-contracts/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L9-solidity-by-example/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L2-data-type-and-variables/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L7-events-and-logs/index.html",
    "./docs/S03-smart-contracts/M2-solidity/L5-contract-structure/index.html",
    "./docs/S03-smart-contracts/M3-python/L2-vyper-overview/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L2-inter-contract-execution/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L5-access-control/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L8-add-material-upgradable-contracts/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L3-inheritance-and-interfaces/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L7-upgradable-contracts/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L1-intro-smart-contracts/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L6-general-finance/index.html",
    "./docs/S03-smart-contracts/M4-design-patterns/L9-optimizing-gas/index.html",
    "./docs/S03-smart-contracts/M5-exercises/L2/index.html",
    "./docs/S03-smart-contracts/M5-exercises/L1/index.html",
    "./docs/S03-smart-contracts/M6-security/L2a-sc-pitfalls-and-attacks/index.html",
    "./docs/S03-smart-contracts/M6-security/L2b-tx-origin-attack/index.html",
    "./docs/S03-smart-contracts/M6-security/L4-tdd-and-truffle-tests/index.html",
    "./docs/S03-smart-contracts/M6-security/L2-solidity-pitfalls-and-attacks/index.html",
    "./docs/S03-smart-contracts/M6-security/L3-sc-checklist/index.html",
    "./docs/S03-smart-contracts/M6-security/L1-sc-best-practices/index.html",
    "./docs/S03-smart-contracts/M6-security/L2d-reentrancy-attack/index.html",
    "./docs/S03-smart-contracts/M6-security/L2e-int-under-over-attack/index.html",
    "./docs/S03-smart-contracts/M6-security/L2c-dos-attack/index.html",
    "./docs/S04-developer-tooling/M1-intro/L2-features-of-dapp-dev/index.html",
    "./docs/S04-developer-tooling/M1-intro/L3-trad-vs-dapp-dev/index.html",
    "./docs/S04-developer-tooling/M1-intro/L1-users-in-mental-model/index.html",
    "./docs/S04-developer-tooling/M6-exercise/index.html",
    "./docs/S09-beyond-code/M4-spirit/index.html",
    "./docs/S09-beyond-code/M3-continuing-ed/index.html",
    "./docs/S09-beyond-code/M1-EIPs/index.html",
    "./docs/S09-beyond-code/M2-ethics/index.html",
    "./docs/S11-what-now/index.html",
    "./docs/S12-final-project/index.html"
]

i=0
converted_texts=[]

for fp in files_path:
    # Open file
    with open("Blockchain-Developer-Bootcamp/" + fp[2:], 'r+', encoding='utf-8') as f:
        # Read file and save in array
        lines = f.read().splitlines()
        
        # Save text between <!-- Title goes below: --> & <!-- Be sure to alter the link below to add in correct Module and Lesson Number -->
        
        text_start=-1
        for i in range(len(lines)):
            if lines[i].replace(' ','')=="<!-- Title goes below: -->".replace(' ',''):
                text_start=i
                break
        
        text_end=-1
        for i in range(len(lines)):
            if lines[i].strip().replace(' ','')=="<!-- Be sure to alter the link below to add in correct Module and Lesson Number -->".replace(' ',''):
                text_end=i
                break
        
        # Convert to md
        converted_text=md(''.join(lines[text_start:text_end+1]))
    
        ## Add '{target=_blank}' to links
        # Search for links but exclude images (link begins with !)
        links=re.findall("[^!]\[.*?\]\(.*?\)",converted_text)
        # Replace the text with text+{target=_blank}
        for l in links:
            print(l)
            converted_text=converted_text.replace(l,l+"{target=_blank}")

        # Save Converted Text
        converted_texts.append(converted_text)
        f.seek(0)
        f.write(converted_text)
        f.truncate()
        
# Rename file from *.html to *.md and update content
from os import rename
for fp in files_path:
    rename(r"Blockchain-Developer-Bootcamp/" + fp[2:],r"Blockchain-Developer-Bootcamp/" + fp[2:].split('.')[0] + '.md')
```

**Comment by ConsenSys-Academy** [comment]
@CodeFrite Thank you so much for all this. I haven't been able to take a close look, but there have been no alarm bells from the first merge.

Could I suggest a way forward?

Would you mind breaking up the conversion into the different modules, again, so it's not monolithic? That way we can merge them incrementally and check to make sure they don't break. We can keep this PR open as a tracking mechanism!

Thank you again so much for this work. Thank you as well for understanding about the need to roll it out gradually!

Let me know what you think

**Comment by CodeFrite** [comment]
Hello,

Sorry for the late reply, while preparing the next pull request I noticed the following issue: In some cases, the text after an image is not properly rendered. In my first pull request I see the issue twice in this file only (I can correct it by hand and submit a new pull request if needed): 

**Merged file containing the issue:** https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/blob/staging/docs/S01-fundamentals/M1-cryptography/L4-hashing-additional/index.md

**First appearance: missing new line after image**

image

**Second appearance: header not rendered correctly**

image

There is either a problem in my call to the mardownify.py library I used to convert from html to md, or in some cases depending on what follows an image, there may be a defect in the library (maybe similar/linked to this: https://github.com/matthewwithanm/python-markdownify/issues/31).

I propose that I check first the call in my code (I'll keep you posted).

If I see no error in the code, I will proceed with the next batch and : 

1. check manually that all the files where correctly rendered by comparing with https://courses.consensys.net/courses/take/blockchain-developer-bootcamp-registration-2021/ rendering 
2. if necessary adapt manually the formatting below an image
3. and only after I will submit the pull request

If you are ok with this, I propose to split the work into the following batches:

S01M1 (Next pull request)
       "./docs/S01-fundamentals/M1-cryptography/L8-crypto-wars-history/index.html",
        "./docs/S01-fundamentals/M1-cryptography/L6-digital-sig-additional/index.html",
        "./docs/S01-fundamentals/M1-cryptography/L8a-crypto-wars-video/index.html",
        "./docs/S01-fundamentals/M1-cryptography/L5-digital-sig/index.html",
        "./docs/S01-fundamentals/M1-cryptography/L7a-eth-101/index.html",
        "./docs/S01-fundamentals/M1-cryptography/L7-crypto-fundamentals-playground/index.html"

S01M2
        "./docs/S01-fundamentals/M2-consensus/L9-blockchain-fork/index.html",
        "./docs/S01-fundamentals/M2-consensus/L2-consensus-additional/index.html",
        "./docs/S01-fundamentals/M2-consensus/L11-consensus-conclusion/index.html",
        "./docs/S01-fundamentals/M2-consensus/L1-consensus-intro/index.html",
        "./docs/S01-fundamentals/M2-consensus/L8-pow-in-ethereum/index.html",
        "./docs/S01-fundamentals/M2-consensus/L5-trustless-consensus/index.html",
        "./docs/S01-fundamentals/M2-consensus/L10-alt-consensus/index.html",
        "./docs/S01-fundamentals/M2-consensus/L6-what-is-a-block/index.html",
        "./docs/S01-fundamentals/M2-consensus/L3-raft/index.html",
        "./docs/S01-fundamentals/M2-consensus/L7-chain-of-blocks/index.html",
        "./docs/S01-fundamentals/M2-consensus/L4-nodes-and-networks/index.html"

S01M3-M4
        "./docs/S01-fundamentals/M3-ag-blockchain/L1-mental-model/index.html",
        "./docs/S01-fundamentals/M3-ag-blockchain/L4-when-to-use/index.html",
        "./docs/S01-fundamentals/M3-ag-blockchain/L2-configurations/index.html",
        "./docs/S01-fundamentals/M3-ag-blockchain/L3-public-private-networks/index.html"
        "./docs/S01-fundamentals/M4-bitcoin/L1-history-and-development/index.html",

S01M5
        "./docs/S01-fundamentals/M5-wallets/L1-what-is-a-wallet/index.html",
        "./docs/S01-fundamentals/M5-wallets/L2-intro-to-mm/index.html",
        "./docs/S01-fundamentals/M5-wallets/L4-secure-extensible-javascript/index.html",
        "./docs/S01-fundamentals/M5-wallets/L5-mm-workshop/index.html",
        "./docs/S01-fundamentals/M5-wallets/L3-mm-lavamoat/index.html",
        "./docs/S01-fundamentals/M5-wallets/L3-security-considerations/index.html"

S02M1-M2
        "./docs/S02-ethereum/M1-background/index.html"
        "./docs/S02-ethereum/M2-accounts/L3-nodes/index.html",
        "./docs/S02-ethereum/M2-accounts/L2-generating-accounts/index.html",
        "./docs/S02-ethereum/M2-accounts/L1-accounts/index.html",

S02M3
        "./docs/S02-ethereum/M3-state/L3-eth-structure/index.html",
        "./docs/S02-ethereum/M3-state/L2-gas-and-fees/index.html",
        "./docs/S02-ethereum/M3-state/L8-networks/index.html",
        "./docs/S02-ethereum/M3-state/L6-playing-with-merkle-trees/index.html",
        "./docs/S02-ethereum/M3-state/L4-txn-tutorial/index.html",
        "./docs/S02-ethereum/M3-state/L7-1559/index.html",
        "./docs/S02-ethereum/M3-state/L1-txns/index.html",
        "./docs/S02-ethereum/M3-state/L5-merkle-trees/index.html",

S03M1-M2
        "./docs/S03-smart-contracts/M1-mental-model/L1-mental-model-sc/index.html",
        "./docs/S03-smart-contracts/M2-intro-to-truffle/L2-intro-tutorial/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L4-storage-and-memory/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L6-abi/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L1-background-context/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L3-functions/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L8-factory-contracts/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L9-solidity-by-example/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L2-data-type-and-variables/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L7-events-and-logs/index.html",
        "./docs/S03-smart-contracts/M2-solidity/L5-contract-structure/index.html",

S03M3-M4
        "./docs/S03-smart-contracts/M3-python/L2-vyper-overview/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L2-inter-contract-execution/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L5-access-control/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L8-add-material-upgradable-contracts/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L3-inheritance-and-interfaces/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L7-upgradable-contracts/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L1-intro-smart-contracts/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L6-general-finance/index.html",
        "./docs/S03-smart-contracts/M4-design-patterns/L9-optimizing-gas/index.html",
   
S03M5-M6
        "./docs/S03-smart-contracts/M5-exercises/L2/index.html",
        "./docs/S03-smart-contracts/M5-exercises/L1/index.html",
        "./docs/S03-smart-contracts/M6-security/L2a-sc-pitfalls-and-attacks/index.html",
        "./docs/S03-smart-contracts/M6-security/L2b-tx-origin-attack/index.html",
        "./docs/S03-smart-contracts/M6-security/L4-tdd-and-truffle-tests/index.html",
        "./docs/S03-smart-contracts/M6-security/L2-solidity-pitfalls-and-attacks/index.html",
        "./docs/S03-smart-contracts/M6-security/L3-sc-checklist/index.html",
        "./docs/S03-smart-contracts/M6-security/L1-sc-best-practices/index.html",
        "./docs/S03-smart-contracts/M6-security/L2d-reentrancy-attack/index.html",
        "./docs/S03-smart-contracts/M6-security/L2e-int-under-over-attack/index.html",
        "./docs/S03-smart-contracts/M6-security/L2c-dos-attack/index.html",

S04
        "./docs/S04-developer-tooling/M1-intro/L2-features-of-dapp-dev/index.html",
        "./docs/S04-developer-tooling/M1-intro/L3-trad-vs-dapp-dev/index.html",
        "./docs/S04-developer-tooling/M1-intro/L1-users-in-mental-model/index.html",
        "./docs/S04-developer-tooling/M6-exercise/index.html",

S09 & S11 & S12
        "./docs/S09-beyond-code/M4-spirit/index.html",
        "./docs/S09-beyond-code/M3-continuing-ed/index.html",
        "./docs/S09-beyond-code/M1-EIPs/index.html",
        "./docs/S09-beyond-code/M2-ethics/index.html",
        "./docs/S11-what-now/index.html",
        "./docs/S12-final-project/index.html"

. : Best Regards : .

Hadi

**Comment by CodeFrite** [comment]
Hello,

I have been able to adapt my script to get the expected behavior. Please find here, the next pull request for the subject: https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/pull/145

It contains the converted files for the second batch:

S01M1
"./docs/S01-fundamentals/M1-cryptography/L8-crypto-wars-history/index.html",
"./docs/S01-fundamentals/M1-cryptography/L6-digital-sig-additional/index.html",
"./docs/S01-fundamentals/M1-cryptography/L8a-crypto-wars-video/index.html",
"./docs/S01-fundamentals/M1-cryptography/L5-digital-sig/index.html",
"./docs/S01-fundamentals/M1-cryptography/L7a-eth-101/index.html",
"./docs/S01-fundamentals/M1-cryptography/L7-crypto-fundamentals-playground/index.html"

It also contains the manual corrections for the layout issues that I introduced with my first pull request. Sorry for that!

. : Best Regards : .

Hadi

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the third batch here : https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/pull/154.

The following files were converted:

**S01M2**
"./docs/S01-fundamentals/M2-consensus/L1-consensus-intro/index.html"
"./docs/S01-fundamentals/M2-consensus/L2-consensus-additional/index.html"
"./docs/S01-fundamentals/M2-consensus/L3-raft/index.html"
"./docs/S01-fundamentals/M2-consensus/L4-nodes-and-networks/index.html"
"./docs/S01-fundamentals/M2-consensus/L5-trustless-consensus/index.html"
"./docs/S01-fundamentals/M2-consensus/L6-what-is-a-block/index.html"
"./docs/S01-fundamentals/M2-consensus/L7-chain-of-blocks/index.html"
"./docs/S01-fundamentals/M2-consensus/L8-pow-in-ethereum/index.html"
"./docs/S01-fundamentals/M2-consensus/L9-blockchain-fork/index.html"
"./docs/S01-fundamentals/M2-consensus/L10-alt-consensus/index.html"
"./docs/S01-fundamentals/M2-consensus/L11-consensus-conclusion/index.html"

. : Best Regards : .

Hadi Sakali

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the third batch here : #161.

The following files were converted:

S01M3-M4
"./docs/S01-fundamentals/M3-ag-blockchain/L1-mental-model/index.html",
"./docs/S01-fundamentals/M3-ag-blockchain/L4-when-to-use/index.html",
"./docs/S01-fundamentals/M3-ag-blockchain/L2-configurations/index.html",
"./docs/S01-fundamentals/M3-ag-blockchain/L3-public-private-networks/index.html"
"./docs/S01-fundamentals/M4-bitcoin/L1-history-and-development/index.html",

. : Best Regards : .

Hadi Sakali

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the 5th batch here : #165 .

The following files were converted:

S01M5
"./docs/S01-fundamentals/M5-wallets/L1-what-is-a-wallet/index.html"
"./docs/S01-fundamentals/M5-wallets/L2-intro-to-mm/index.html"
"./docs/S01-fundamentals/M5-wallets/L4-secure-extensible-javascript/index.html"
"./docs/S01-fundamentals/M5-wallets/L5-mm-workshop/index.html"
"./docs/S01-fundamentals/M5-wallets/L3-mm-lavamoat/index.html"
"./docs/S01-fundamentals/M5-wallets/L3-security-considerations/index.html"

. : Best Regards : .

CodeFrite

**Comment by ConsenSys-Academy** [comment]
You are totally incredible @CodeFrite !! Let's wait a few days to make sure new conversions are okay but I think we're in the clear!

**Comment by ConsenSys-Academy** [comment]
@CodeFrite Wanted to check in about this!

**Comment by CodeFrite** [comment]
Hello @ConsenSys-Academy ,

I have created the 2 next pull requests on separate branches (#206 & #207). 

6 more to go and we should be done with #108 !

I'll try to process 2 batches per days in order to wrap up by the end of the week.

. : Best Regards : .

CodeFrite

**Comment by CodeFrite** [comment]
Hello,

Sorry, lately I couldn't work much on this issue. I have a few days off next week. I'll make sure to finish this next week with pleasure.

. : Best Regards : .

CodeFrite

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the 9th batch here : #214. 

4 more to go :)

The following files were converted:

S03M3-M4
./docs/S03-smart-contracts/M3-python/L2-vyper-overview/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L2-inter-contract-execution/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L5-access-control/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L8-add-material-upgradable-contracts/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L3-inheritance-and-interfaces/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L7-upgradable-contracts/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L1-intro-smart-contracts/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L6-general-finance/index.html"
./docs/S03-smart-contracts/M4-design-patterns/L9-optimizing-gas/index.html"

. : Best Regards : .

CodeFrite

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the 9th batch here : #216.

3 more to go :)

The following files were converted:

S03M5
./docs/S03-smart-contracts/M5-exercises/L2/index.html
./docs/S03-smart-contracts/M5-exercises/L1/index.html

. : Best Regards : .

CodeFrite

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the 10th batch here : #217.

2 more to go :)

The following files were converted:

S03M6
./docs/S03-smart-contracts/M6-security/L1-sc-best-practices/index.html
./docs/S03-smart-contracts/M6-security/L2-solidity-pitfalls-and-attacks/index.html
./docs/S03-smart-contracts/M6-security/L2a-sc-pitfalls-and-attacks/index.html
./docs/S03-smart-contracts/M6-security/L2b-tx-origin-attack/index.html
./docs/S03-smart-contracts/M6-security/L2c-dos-attack/index.html
./docs/S03-smart-contracts/M6-security/L2d-reentrancy-attack/index.html
./docs/S03-smart-contracts/M6-security/L2e-int-under-over-attack/index.html
./docs/S03-smart-contracts/M6-security/L3-sc-checklist/index.html
./docs/S03-smart-contracts/M6-security/L4-tdd-and-truffle-tests/index.html

. : Best Regards : .

CodeFrite

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the 10th batch here : #218.

1 more to go :)

The following files were converted:

S04M1 & M6
./docs/S04-developer-tooling/M1-intro/L2-features-of-dapp-dev/index.html
./docs/S04-developer-tooling/M1-intro/L3-trad-vs-dapp-dev/index.html
./docs/S04-developer-tooling/M1-intro/L1-users-in-mental-model/index.html
./docs/S04-developer-tooling/M6-exercise/index.html

. : Best Regards : .

CodeFrite

**Comment by CodeFrite** [comment]
Hello,

Please find the PR for the 12th batch here : #219.

The following files were converted:

S09-S11-S12
./docs/S09-beyond-code/M4-spirit/index.html
./docs/S09-beyond-code/M3-continuing-ed/index.html
./docs/S09-beyond-code/M1-EIPs/index.html
./docs/S09-beyond-code/M2-ethics/index.html
./docs/S11-what-now/index.html
./docs/S12-final-project/index.html

. : Best Regards : .

CodeFrite

**Comment by CodeFrite** [comment]
Hello @ConsenSys-Academy ,

I think that we are done with this ticket. Please do not hesitate to link me any remaining files that need to be converted. I'll take care of them with pleasure.

Thank you for all :)

. : Best Regards : .

CodeFrite

**Comment by ConsenSys-Academy** [comment]
@CodeFrite Thank you for everything! Want to take a stab at https://github.com/ConsenSys-Academy/basic-training ???

**Pull request closed without merging**
