### PR TITLE
82 QuestBook-Learn Solidity

### PR DESCRIPTION
**Pull request by miield**
### Added Questbook discord, a discord server focused on beginners in Solidity

### CODE REVIEW

**Comment by cooganb** [comment]
Hey there! Your previous PR created a conflict with this one! Next time you should submit them together!

Do a git pull on the main repo to update this and then we can merge

**Comment by ConsenSys-Academy** [comment]
You can update it with the following flow:

git remote add upstream https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp
git fetch upstream
git merge upstream/typo
git push origin typo

**Comment by cooganb** [comment]
@miield Hey! Lmk if you'd like to try and fix this, otherwise I'll close in 24hrs. It's really valuable contribution, would love to have it in

**Comment by miield** [comment]
Apologise, I am just seeing the mail. Kindly give me 24hrs to work on it. I
have some technical issues.

Thank you
Miield

**Comment by ConsenSys-Academy** [comment]
Sounds good!

**Comment by miield** [comment]
@cooganb I am getting this error

merge: upstream/typo - not something we can merge

**Pull request merged**
