### PR TITLE
Edit grammar in S01-M2-L2 consensus materials

### PR DESCRIPTION
**Pull request by wushenshen**
I added some Oxford commas, is there a preference?

### CODE REVIEW

**Comment by cooganb** [comment]
hey! gonna actually close this, not really a typo, more preference! ty though!

**Comment by wushenshen** [comment]
@cooganb the Oxford comma edits were only a small part of the PR, btw - the rest included fixes for real typos.

**Comment by cooganb** [comment]
Sorry about that! Will check out tomorrow!

**Comment by ConsenSys-Academy** [comment]
ty!

**Pull request merged**
