### PR TITLE
Added study guides

### PR DESCRIPTION
**Pull request by adilmezghouti**

### CODE REVIEW

**Comment by lonasozo** [comment]
This is an awesome work! I could start work to Italian translations too 😁
I make some suggestions: 
- Could be better if assets will have always the same name? So we can have a lesser risk to have broken link when someone add a new translation (Example: Study_Guides/French/chapitre2_image1.png -> Study_Guides/French/cap2_image1.png)
- English docx should be converted to Markdown, correct? If yes, I can try to help you

**Comment by adilmezghouti** [comment]
@lonasozo Thanks. I agree with you. We can even move those images to a location so that all future translations can use the same images. Regarding the English ones, we might need to run that by @ConsenSys-Academy to see if there is value in converting them to markdown.

**Comment by lonasozo** [comment]
Clear! About images if the assets will not change based on language, yes, one directory will be perfect 😁
Just another thing, maybe for the languages paths it's better to use more standards way to identify them, like:
English -> en
French -> fr
Italian -> it
...and so on, just personal opinion 🙏

**Comment by ConsenSys-Academy** [comment]
@adilmezghouti @lonasozo Hey friends! This conversation is awesome. @lonasozo If you wanted to convert the English to markdown, that would be awesome. We need to do this anyway. 

@adilmezghouti Would you be able to be separate the English and French exercises into two different branches and do another PR with just the English and another with just the French?

Really appreciate all this work, yall!

**Comment by lonasozo** [comment]
@ConsenSys-Academy sure I can, @adilmezghouti let me know, if you are already working on that for me it's not a problem 😉

**Comment by adilmezghouti** [comment]
@ConsenSys-Academy No problem. I am on it.

**Comment by adilmezghouti** [comment]
@ConsenSys-Academy I just updated this PR to only contain the English style guides. I will submit another PR with the French version.

**Comment by lonasozo** [comment]
@adilmezghouti I think could be better if you rename this Pull Request based on the new updates. Haven't got time to check new files, let me know if you are able to connect english docx to markdowns 🚀

**Comment by adilmezghouti** [comment]
@lonasozo Thanks for the feedback. I fixed the title and converted docx to markdown. cc @ConsenSys-Academy

**Comment by ConsenSys-Academy** [comment]
@adilmezghouti Thank you so much for all this!

**Pull request merged**
